//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int IdFlat { get; set; }
        public int BuildingNumberOfRoom { get; set; }
        public decimal Price { get; set; }
        public int NumberOfRooms { get; set; }
        public int Area { get; set; }
        public int FloorNumber { get; set; }
        public int EntranceNumber { get; set; }
        public int IdSkyscraper { get; set; }
        public byte[] ImagePreview { get; set; }
    
        public virtual SkyScraper SkyScraper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
