//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Flats = new HashSet<Flat>();
        }
    
        public int IdRequest { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public decimal MaximumPrice { get; set; }
        public int NumberOfRooms { get; set; }
        public int MinimumArea { get; set; }
        public Nullable<int> MaximumArea { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int IdDistrict { get; set; }
        public int IdEmployee { get; set; }
        public int IdClient { get; set; }
        public Nullable<int> IdRequestStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual District District { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flats { get; set; }
    }
}
