//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkyScraper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkyScraper()
        {
            this.Flats = new HashSet<Flat>();
        }
    
        public int IdSkyscraper { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int NumberOfFloors { get; set; }
        public int NumberOfEntrances { get; set; }
        public int NumberOfApartments { get; set; }
        public int IdDistrict { get; set; }
        public int IdMaterial { get; set; }
        public int IdDeveloper { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flats { get; set; }
        public virtual Material Material { get; set; }
    }
}
